"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!roq3xwgaa&gkmr-)yx=8p!y=wg815_10!5s!5g4)^5qp5im(o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'userprofile',
]


# Jazzmin Admin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Profile Admin",
    "site_header": "Profile Administration",
    "site_brand": "Profile Administration",
    "show_sidebar": True,
    "site_logo": None,
    "login_logo": None,
    "copyright": "Md Abdullah Al Fahim",
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    'hide_models': ['auth.group', 'auth.user'],
    "related_modal_active": True,
    'order_with_respect_to': [
        'userprofile',
        # Models
        'userprofile.Profile',
        'userprofile.BackgroundImage',
        'userprofile.Education',
        'userprofile.Certification',
        'userprofile.SkillCategory',
        'userprofile.Skill',
        'userprofile.Experience',
        'userprofile.ProjectCategory',
        'userprofile.Project',
        'userprofile.Award',
        'userprofile.ContactMessage',
    ],
     "icons": {
        "userprofile.Profile": "fas fa-user-tie",
        "userprofile.BackgroundImage": "fas fa-image",
        "userprofile.Education": "fas fa-graduation-cap",
        "userprofile.Certification": "fas fa-certificate",
        "userprofile.SkillCategory": "fas fa-tags",
        "userprofile.Skill": "fas fa-code",
        "userprofile.Experience": "fas fa-briefcase",
        "userprofile.ProjectCategory": "fas fa-layer-group",
        "userprofile.Project": "fas fa-laptop-file",
        "userprofile.Award": "fas fa-trophy",
        "userprofile.ContactMessage": "fas fa-envelope",
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-primary",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, etc.)
STATIC_URL = '/static/'

# Folders where you store static files (in development)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Folder where static files will be collected (by collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'Full',
        'toolbar_Full': [
            ['Undo', 'Redo'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['RemoveFormat', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote', 'CreateDiv'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar', 'Smiley'],
            ['Maximize', 'ShowBlocks', 'Source']
        ],
        'height': 400,
        'width': '100%',
        'extraPlugins': ','.join([
            'font',           # Enables Font and FontSize
            'colorbutton',    # TextColor, BGColor
            'justify',        # Justify buttons
            'div',            # CreateDiv
            'pastefromword',  # Paste from Word
            'showblocks',     # Show block elements
            'smiley',         # Emoji support
            'find',           # Find/Replace
            'tabletools',     # Advanced table options
            'format',         # Format dropdown
        ]),
    },
}
