# Generated by Django 5.2.4 on 2025-07-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_award_icon_class_alter_award_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='color',
        ),
    ]
