# Generated by Django 5.2.4 on 2025-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_award_profile_remove_certification_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
