# Generated by Django 5.2.4 on 2025-07-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='color_scheme',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon_class',
            field=models.CharField(choices=[('fas fa-chart-pie', 'Chart Pie'), ('fas fa-robot', 'Robot'), ('fas fa-database', 'Database'), ('fas fa-cloud', 'Cloud'), ('fas fa-code', 'Code'), ('fas fa-chart-bar', 'Chart Bar'), ('fas fa-brain', 'AI'), ('fas fa-server', 'Server'), ('fas fa-network-wired', 'Network'), ('fas fa-laptop-code', 'Development')], default='fas fa-code', max_length=50),
        ),
    ]
