# Generated by Django 5.2.4 on 2025-07-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_skillcategory_color_scheme_skillcategory_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
