# Generated by Django 5.2.4 on 2025-07-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(choices=[('DA', 'Data Analysis'), ('ML', 'Machine Learning'), ('WEB', 'Web Development')], default='DA', max_length=5),
        ),
    ]
