# Generated by Django 5.2.4 on 2025-07-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_projectcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='award',
            name='icon_class',
            field=models.CharField(choices=[('fas fa-trophy', 'Trophy'), ('fas fa-award', 'Award'), ('fas fa-medal', 'Medal'), ('fas fa-certificate', 'Certificate'), ('fas fa-star', 'Star')], default='fas fa-award', max_length=20),
        ),
        migrations.AlterField(
            model_name='award',
            name='issuing_organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
